"""source_updated_at on every sourced table

Revision ID: b5c0673a8afc
Revises: b1f0c2d3e4a5
Create Date: 2026-09-23 21:58:51.308722+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b5c0673a8afc"
down_revision: str | None = "b1f0c2d3e4a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "customers",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_levels",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "inventory_movements",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "locations",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "order_lines",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "orders", sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "refund_lines",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "refunds",
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refunds", "source_updated_at")
    op.drop_column("refund_lines", "source_updated_at")
    op.drop_column("orders", "source_updated_at")
    op.drop_column("order_lines", "source_updated_at")
    op.drop_column("locations", "source_updated_at")
    op.drop_column("inventory_movements", "source_updated_at")
    op.drop_column("inventory_levels", "source_updated_at")
    op.drop_column("customers", "source_updated_at")
    op.drop_column("categories", "source_updated_at")
    # ### end Alembic commands ###
