"""proactive features: insights, jobs, notifications, vendors, payments

Everything the feature pack needs, in one step, because none of it is useful
on its own.

Four canonical additions the adapters now fill: `vendors` and `variant_vendors`
(who the shop buys from and on what terms, which is what turns a reorder
suggestion into a purchase order), `payments` (takings by tender, for the
month-end packet), and `staff_hours`, which no POS knows and the owner types in.

The rest is the proactive layer: `insights` and `insight_outcomes`, the
`job_runs` log that makes the worker idempotent, `notification_prefs` and
`outbound_messages`, and one table family per feature — purchase orders,
rescue actions, series, and month-end packets.

Create-only: nothing existing is altered or dropped.

Revision ID: 35e1506805f2
Revises: 502d25301b8a
Create Date: 2026-09-24 05:21:11.789224+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '35e1506805f2'
down_revision: str | None = '502d25301b8a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warn', 'urgent', name='insight_severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('dollar_impact', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('new', 'seen', 'acted', 'dismissed', 'expired', 'snoozed', name='insight_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('acted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dismissed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('snoozed_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('was_useful', sa.Boolean(), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dollar_impact is null or dollar_impact >= 0', name=op.f('ck_insights_dollar_impact_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_insights_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights')),
    sa.UniqueConstraint('tenant_id', 'dedupe_key', name='uq_insights_tenant_dedupe')
    )
    op.create_index('ix_insights_tenant_kind_created', 'insights', ['tenant_id', 'kind', 'created_at'], unique=False)
    op.create_index('ix_insights_tenant_status', 'insights', ['tenant_id', 'status'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'skipped', name='job_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_job_runs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    sa.UniqueConstraint('tenant_id', 'job', 'due_at', name='uq_job_runs_tenant_job_due')
    )
    op.create_index('ix_job_runs_job_status', 'job_runs', ['job', 'status'], unique=False)
    op.create_index('ix_job_runs_tenant_started', 'job_runs', ['tenant_id', 'started_at'], unique=False)
    op.create_table('month_end_packets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('figures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emailed_to', sa.String(length=320), nullable=True),
    sa.Column('emailed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_month_end_packets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_month_end_packets')),
    sa.UniqueConstraint('tenant_id', 'period_start', name='uq_month_end_packets_period')
    )
    op.create_index('ix_month_end_packets_tenant_period', 'month_end_packets', ['tenant_id', 'period_start'], unique=False)
    op.create_table('notification_prefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('allow_urgent_in_quiet_hours', sa.Boolean(), nullable=False),
    sa.Column('max_per_day', sa.Integer(), nullable=False),
    sa.Column('wants_digest', sa.Boolean(), nullable=False),
    sa.Column('unsubscribed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_per_day >= 0', name=op.f('ck_notification_prefs_max_per_day_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notification_prefs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_prefs')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_notification_prefs_tenant_email')
    )
    op.create_index('ix_notification_prefs_tenant', 'notification_prefs', ['tenant_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalised_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'confirmed', 'rejected', name='series_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('detected_by', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('auto_send', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_series_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('tenant_id', 'normalised_name', name='uq_series_tenant_name')
    )
    op.create_index('ix_series_tenant_status', 'series', ['tenant_id', 'status'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('account_number', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_vendors_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('tenant_id', 'source', 'external_id', name='uq_vendors_source_external')
    )
    op.create_index('ix_vendors_tenant', 'vendors', ['tenant_id'], unique=False)
    op.create_table('insight_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('measured_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('before_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('after_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('attributed_revenue', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_insight_outcomes_insight_id_insights'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_insight_outcomes_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insight_outcomes'))
    )
    op.create_index('ix_insight_outcomes_insight', 'insight_outcomes', ['insight_id'], unique=False)
    op.create_index('ix_insight_outcomes_tenant_measured', 'insight_outcomes', ['tenant_id', 'measured_at'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'console', name='notify_channel', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', 'suppressed', name='message_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_outbound_messages_insight_id_insights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_outbound_messages_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_messages'))
    )
    op.create_index('ix_outbound_messages_tenant_created', 'outbound_messages', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_outbound_messages_tenant_kind', 'outbound_messages', ['tenant_id', 'kind'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('vendor_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'received', 'canceled', name='purchase_order_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('expected_at', sa.Date(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_purchase_orders_insight_id_insights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_purchase_orders_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_purchase_orders_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_purchase_orders_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    op.create_index('ix_purchase_orders_tenant_created', 'purchase_orders', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_purchase_orders_tenant_status', 'purchase_orders', ['tenant_id', 'status'], unique=False)
    op.create_table('series_followers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('contact_key', sa.String(length=320), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('inferred', 'opt_in', name='follower_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('volumes_bought', sa.Integer(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('consent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('consent_source', sa.String(length=32), nullable=True),
    sa.Column('consent_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unsubscribed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=True),
    sa.Column('last_notified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_series_followers_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_followers_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_series_followers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series_followers')),
    sa.UniqueConstraint('tenant_id', 'series_id', 'contact_key', name='uq_series_followers_contact')
    )
    op.create_index('ix_series_followers_series_source', 'series_followers', ['series_id', 'source'], unique=False)
    op.create_table('staff_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('staff_count', sa.SmallInteger(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_staff_hours_shift_ends_after_it_starts')),
    sa.CheckConstraint('staff_count > 0', name=op.f('ck_staff_hours_staff_count_positive')),
    sa.CheckConstraint('weekday between 0 and 6', name=op.f('ck_staff_hours_weekday_in_week')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_staff_hours_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_staff_hours_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_hours')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'weekday', 'start_time', name='uq_staff_hours_slot')
    )
    op.create_index('ix_staff_hours_tenant', 'staff_hours', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tip', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tender', sa.Enum('card', 'cash', 'other', name='tender', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('tenant_id', 'source', 'external_id', name='uq_payments_source_external')
    )
    op.create_index('ix_payments_tenant', 'payments', ['tenant_id'], unique=False)
    op.create_index('ix_payments_tenant_occurred', 'payments', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_payments_tenant_order', 'payments', ['tenant_id', 'order_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=512), nullable=False),
    sa.Column('sku_snapshot', sa.String(length=128), nullable=True),
    sa.Column('suggested_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('on_hand_at_draft', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_purchase_order_lines_quantity_non_negative')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_purchase_order_id_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_purchase_order_lines_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_purchase_order_lines_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines'))
    )
    op.create_index('ix_purchase_order_lines_order', 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_index('ix_purchase_order_lines_tenant_variant', 'purchase_order_lines', ['tenant_id', 'variant_id'], unique=False)
    op.create_table('rescue_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_before', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_after', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('on_hand_before', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('taken_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('measured_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_rescue_actions_insight_id_insights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_rescue_actions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_rescue_actions_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rescue_actions'))
    )
    op.create_index('ix_rescue_actions_tenant_taken', 'rescue_actions', ['tenant_id', 'taken_at'], unique=False)
    op.create_index('ix_rescue_actions_tenant_variant', 'rescue_actions', ['tenant_id', 'variant_id'], unique=False)
    op.create_table('series_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'confirmed', 'rejected', name='series_item_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('parsed_from', sa.String(length=512), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('volume_number > 0', name=op.f('ck_series_items_volume_number_positive')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_items_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_series_items_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_series_items_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series_items')),
    sa.UniqueConstraint('tenant_id', 'variant_id', name='uq_series_items_variant')
    )
    op.create_index('ix_series_items_series', 'series_items', ['series_id'], unique=False)
    op.create_table('variant_vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pack_size', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lead_time_days >= 0', name=op.f('ck_variant_vendors_lead_time_non_negative')),
    sa.CheckConstraint('min_order_qty >= 0', name=op.f('ck_variant_vendors_min_order_qty_non_negative')),
    sa.CheckConstraint('pack_size > 0', name=op.f('ck_variant_vendors_pack_size_positive')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_variant_vendors_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_variant_vendors_variant_id_variants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_variant_vendors_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant_vendors')),
    sa.UniqueConstraint('tenant_id', 'source', 'external_id', name='uq_variant_vendors_source_external'),
    sa.UniqueConstraint('tenant_id', 'variant_id', 'vendor_id', name='uq_variant_vendors_variant_vendor')
    )
    op.create_index('ix_variant_vendors_tenant', 'variant_vendors', ['tenant_id'], unique=False)
    op.create_table('series_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('series_item_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('notified_contact_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('fk_series_releases_insight_id_insights'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_releases_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_item_id'], ['series_items.id'], name=op.f('fk_series_releases_series_item_id_series_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_series_releases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_series_releases_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series_releases')),
    sa.UniqueConstraint('tenant_id', 'series_item_id', name='uq_series_releases_item')
    )
    op.create_index('ix_series_releases_tenant_detected', 'series_releases', ['tenant_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_series_releases_tenant_detected', table_name='series_releases')
    op.drop_table('series_releases')
    op.drop_index('ix_variant_vendors_tenant', table_name='variant_vendors')
    op.drop_table('variant_vendors')
    op.drop_index('ix_series_items_series', table_name='series_items')
    op.drop_table('series_items')
    op.drop_index('ix_rescue_actions_tenant_variant', table_name='rescue_actions')
    op.drop_index('ix_rescue_actions_tenant_taken', table_name='rescue_actions')
    op.drop_table('rescue_actions')
    op.drop_index('ix_purchase_order_lines_tenant_variant', table_name='purchase_order_lines')
    op.drop_index('ix_purchase_order_lines_order', table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index('ix_payments_tenant_order', table_name='payments')
    op.drop_index('ix_payments_tenant_occurred', table_name='payments')
    op.drop_index('ix_payments_tenant', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_staff_hours_tenant', table_name='staff_hours')
    op.drop_table('staff_hours')
    op.drop_index('ix_series_followers_series_source', table_name='series_followers')
    op.drop_table('series_followers')
    op.drop_index('ix_purchase_orders_tenant_status', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_tenant_created', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_outbound_messages_tenant_kind', table_name='outbound_messages')
    op.drop_index('ix_outbound_messages_tenant_created', table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index('ix_insight_outcomes_tenant_measured', table_name='insight_outcomes')
    op.drop_index('ix_insight_outcomes_insight', table_name='insight_outcomes')
    op.drop_table('insight_outcomes')
    op.drop_index('ix_vendors_tenant', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_series_tenant_status', table_name='series')
    op.drop_table('series')
    op.drop_index('ix_notification_prefs_tenant', table_name='notification_prefs')
    op.drop_table('notification_prefs')
    op.drop_index('ix_month_end_packets_tenant_period', table_name='month_end_packets')
    op.drop_table('month_end_packets')
    op.drop_index('ix_job_runs_tenant_started', table_name='job_runs')
    op.drop_index('ix_job_runs_job_status', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_insights_tenant_status', table_name='insights')
    op.drop_index('ix_insights_tenant_kind_created', table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
